### ISSUE TITLE
Foreman-intaller failing due to nil class error during installation

### ISSUE THREAD

**Issue by miroswan** [theforeman/puppet-tftp#37] opened 2016-01-10 07:31 UTC
/Stage[main]/Tftp::Service/Service[tftpd-hpa]: Could not evaluate: undefined method `[]' for nil:NilClass

It appears that an object does not yet exist, but is trying to be accessed.

**Comment by domcleal** [comment] 2016-01-11 08:16
That sounds like a bug in Puppet, try running with --debug and the log should contain a full stack trace.

**Comment by mmoll** [comment] 2016-02-07 02:18
@miroswan ping?

**Comment by kierr** [comment] 2016-02-14 08:13
I seem to be having precisely the same issue, on two independent host systems (one CentOS, one Ubuntu).

This is my installation command:
```
$ /usr/sbin/foreman-installer \
--foreman-locations-enabled \
--enable-foreman-compute-ec2 \
--enable-foreman-compute-gce \
--enable-foreman-compute-ovirt \
--enable-foreman-compute-vmware \
--enable-foreman-compute-libvirt \
--enable-foreman-compute-openstack \
--enable-foreman-compute-rackspace \
--enable-puppet \
--puppet-listen=true \
--puppet-show-diff=true \
--puppet-server-envs-dir=/etc/puppet/environments
```

Here is the debug installation log:
```

tput: No value for $TERM and no -T specified
Debug: Loading facts from /usr/share/foreman-insta: 0 00:00:00
Debug: Puppet::Type::Package::ProviderPortage: fil: 0 0.0/s 00:00:01
Debug: hiera(): Looking up foreman::passenger_ruby: 0 0.0/s 00:00:02
Debug: hiera(): Looking for data source common    : 0 0.0/s 00:00:03
Debug: hiera(): Looking for data source common    : 0 0.0/s 00:00:04
Debug: hiera(): Looking up postgresql::server::ser: 0 0.0/s 00:00:06
Debug: importing '/usr/share/foreman-installer/mod: 0 0.0/s 00:00:07
Debug: importing '/usr/share/foreman-installer/mod: 0 0.0/s 00:00:08
Debug: hiera(): Cannot find datafile /var/lib/hier: 0 0.0/s 00:00:09
Debug: template[/usr/share/foreman-installer/modul: 0 0.0/s 00:00:10
Debug: template[/usr/share/foreman-installer/modul: 0 0.0/s 00:00:11
Debug: Adding relationship from Class[Foreman::Dat: 0 0.0/s 00:00:13
Debug: /User[foreman]: Provider useradd does not s: 0 0.0/s 00:00:14
Debug: Using settings: adding file resource 'priva: 0 0.0/s 00:00:16
Debug: /Stage[main]/Foreman::Config::Passenger/Apa: 0/543, 0%, 0.0/s, elapsed: 00:00:17
 Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install postgresql-client-9.3' returned 100: Reading package lists...
Error: Execution of '/usr/bin/apt-get -q -y -o DPk: 31/543, 5%, 0.5/s, elapsed: 00:00:25, ETA: 00:16:03
 /Stage[main]/Postgresql::Client/Package[postgresql-client]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install postgresql-client-9.3' returned 100: Reading package lists...
Notice: /Stage[main]/Foreman_proxy::Install/Packag: 55/543, 10%, 0.7/s, elapsed: 00:00:45, ETA: 00:11:04
Notice: /Stage[main]/Puppet::Server::Install/Packa: 95/543, 17%, 1.2/s, elapsed: 00:01:00, ETA: 00:06:18
 Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install postgresql-9.3' returned 100: Reading package lists...
Error: Execution of '/usr/bin/apt-get -q -y -o DPk: 99/543, 18%, 1.2/s, elapsed: 00:01:12, ETA: 00:05:58
 /Stage[main]/Postgresql::Server::Install/Package[postgresql-server]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install postgresql-9.3' returned 100: Reading package lists...
Notice: /Stage[main]/Foreman_proxy::Install/Packag: 100/543, 18%, 1.2/s, elapsed: 00:01:53, ETA: 00:05:56
 Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install foreman-postgresql' returned 100: Reading package lists...
Error: Execution of '/usr/bin/apt-get -q -y -o DPk: 103/543, 18%, 1.2/s, elapsed: 00:03:42, ETA: 00:05:52
 /Stage[main]/Foreman::Install/Package[foreman-postgresql]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install foreman-postgresql' returned 100: Reading package lists...
Notice: /Stage[main]/Tftp::Install/Package[syslinu: 117/543, 21%, 0.8/s, elapsed: 00:04:03, ETA: 00:08:35
	Notice: /Stage[main]/Apache/Package[httpd]/ensure:: 123/543, 22%, 0.7/s, elapsed: 00:04:33, ETA: 00:10:39
Notice: /Stage[main]/Apache::Mod::Negotiation/File: 160/543, 29%, 0.7/s, elapsed: 00:04:34, ETA: 00:09:43
Notice: /Stage[main]/Puppet::Server::Install/Packa: 263/543, 48%, 1.8/s, elapsed: 00:04:48, ETA: 00:02:39
Notice: /Stage[main]/Apache::Mod::Passenger/Apache: 291/543, 53%, 1.9/s, elapsed: 00:05:16, ETA: 00:02:15
Notice: /Stage[main]/Tftp::Install/Package[tftpd-h: 326/543, 60%, 2.2/s, elapsed: 00:05:33, ETA: 00:01:38
 /Stage[main]/Tftp::Service/Service[tftpd-hpa]: Could not evaluate: undefined method `[]' for nil:NilClass
Notice: /Stage[main]/Apache/Apache::Vhost[default]: 373/543, 68%, 2.2/s, elapsed: 00:05:34, ETA: 00:01:17
Notice: /Stage[main]/Foreman::Cli/Package[foreman-: 380/543, 69%, 2.6/s, elapsed: 00:05:57, ETA: 00:01:03
Debug: Exec[concat_05-foreman-ssl.conf](provider=p: 533/543, 98%, 2.6/s, elapsed: 00:05:58, ETA: 00:00:03
Notice: /Stage[main]/Apache/Concat[/etc/apache2/po: 542/543, 99%, 2.6/s, elapsed: 00:05:59
Debug: Exec[puppet_server_config-generate_ca_cert]: 542/543, 99%, 11.3/s, elapsed: 00:06:00
Notice: /Stage[main]/Puppet::Server::Config/Exec[p: 542/543, 99%, 11.3/s, elapsed: 00:06:09
Notice: /Stage[main]/Puppet::Agent::Service/Servic: 542/543, 99%, 9.7/s, elapsed: 00:06:12
Notice: /Stage[main]/Foreman_proxy::Config/Foreman: 542/543, 99%, 9.7/s, elapsed: 00:06:13
Notice: /Stage[main]/Foreman_proxy::Service/Servic: 542/543, 99%, 9.6/s, elapsed: 00:06:15
Notice: /Stage[main]/Foreman_proxy::Register/Forem: 542/543, 99%, 9.6/s, elapsed: 00:06:17
 /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[hostname.example.com]: Failed to call refresh: Proxy hostname.example.com cannot be registered (Could not load data from https://hostname.example.com
 /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[hostname.example.com]: Proxy hostname.example.com cannot be registered (Could not load data from https://hostname.example.com
 Could not find a suitable provider for foreman_config_entry
Done                                              : 543/543, 100%, 9.3/s, elapsed: 00:06:21
Done                                              : 543/543, 100%, 9.3/s, elapsed: 00:06:21
  Something went wrong! Check the log for ERROR-level output
  * Foreman is running at https://hostname.example.com
      Initial credentials are admin / 6Mkx6SLTHMM27VJ7
  * Foreman Proxy is running at https://hostname.example.com:8443
  * Puppetmaster is running at port 8140
  The full log is at /var/log/foreman-installer/foreman-installer.log
sed: can't read /etc/default/foreman: No such file or directory
 * Stopping puppet agent
   ...done.
 * Stopping web server apache2
 * 
/bin/sh: 1: /etc/init.d/foreman: not found

```
I am actually running this in a docker container, thanks to [gbevan/ubuntu-foreman](https://github.com/gbevan/ubuntu-foreman). But as far as I can tell being in a container shouldn't affect things.

**Comment by mmoll** [comment] 2016-02-14 12:36
@kierr Tha actual logfile would be under /var/log/foreman-installer/foreman-installer.log, but anyway... :)

The main problem I'm seeing here is that the installations of the pgsql packages is failing, so first make sure "apt-get install postgresql-client-9.3 postgresql-9.3: is uceeding and after that "apt-get install foreman-postgresql". Then rerun the installer and, if it does not succeed, look for ERROR lines in the installer log.

**Comment by kierr** [comment] 2016-02-15 01:41
Sure, did see the logfile path at the end of what I posted, which I suppose I should have called stdout, as opposed to stderr :)
```
I did as suggested, and it appears the packages are installed just fine:

# apt-get install postgresql-client-9.3 postgresql-9.3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
postgresql-9.3 is already the newest version.
postgresql-client-9.3 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

# apt-get install foreman-postgresql
Reading package lists... Done
Building dependency tree       
Reading state information... Done
foreman-postgresql is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

# hostname -f
example.hostname.org
```
Having a look at all the ERRORS in the stderr:

```
# cat /var/log/foreman-installer/foreman-installer.log | grep ERROR
[DEBUG 2016-02-15 01:09:51 main] calling :function_validate_re with [["ERROR", "^(UNKNOWN|FATAL|ERROR|WARN|INFO|DEBUG)$"]]
[ERROR 2016-02-15 01:23:47 main]  /Stage[main]/Tftp::Service/Service[tftpd-hpa]: Could not evaluate: undefined method `[]' for nil:NilClass
[ INFO 2016-02-15 01:29:11 main] -# WARN, DEBUG, ERROR, FATAL, INFO, UNKNOWN
[ INFO 2016-02-15 01:29:11 main]  :log_level: ERROR
[ WARN 2016-02-15 01:29:19 main]  /Stage[main]/Foreman::Database::Postgresql/Postgresql::Server::Db[foreman]/Postgresql::Server::Database[foreman]/Exec[/usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='foreman' --template=template0 --encoding 'utf8' --locale=en_US.utf8  'foreman']/returns: createdb: database creation failed: ERROR:  invalid locale name: "en_US.utf8"
[ERROR 2016-02-15 01:29:19 main]  /Stage[main]/Foreman::Database::Postgresql/Postgresql::Server::Db[foreman]/Postgresql::Server::Database[foreman]/Exec[/usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='foreman' --template=template0 --encoding 'utf8' --locale=en_US.utf8  'foreman']: Failed to call refresh: /usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='foreman' --template=template0 --encoding 'utf8' --locale=en_US.utf8  'foreman' returned 1 instead of one of [0]
[ERROR 2016-02-15 01:29:19 main]  /Stage[main]/Foreman::Database::Postgresql/Postgresql::Server::Db[foreman]/Postgresql::Server::Database[foreman]/Exec[/usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='foreman' --template=template0 --encoding 'utf8' --locale=en_US.utf8  'foreman']: /usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='foreman' --template=template0 --encoding 'utf8' --locale=en_US.utf8  'foreman' returned 1 instead of one of [0]
[ERROR 2016-02-15 01:29:19 main]  /Stage[main]/Foreman::Database::Postgresql/Postgresql::Server::Db[foreman]/Postgresql::Server::Database_grant[GRANT foreman - ALL - foreman]/Postgresql::Server::Grant[database:GRANT foreman - ALL - foreman]/Postgresql_psql[grant:database:GRANT foreman - ALL - foreman]: Could not evaluate: Error evaluating 'unless' clause, returned pid 4080 exit 1: 'ERROR:  database "foreman" does not exist
[ERROR 2016-02-15 01:30:01 main]  /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]: Failed to call refresh: /usr/sbin/foreman-rake db:migrate returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:01 main]  /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]: /usr/sbin/foreman-rake db:migrate returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:22 main]  /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]: Failed to call refresh: /usr/sbin/foreman-rake db:seed returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:22 main]  /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]: /usr/sbin/foreman-rake db:seed returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:44 main]  /Stage[main]/Foreman::Database/Foreman::Rake[apipie:cache:index]/Exec[foreman-rake-apipie:cache:index]: Failed to call refresh: /usr/sbin/foreman-rake apipie:cache:index returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:44 main]  /Stage[main]/Foreman::Database/Foreman::Rake[apipie:cache:index]/Exec[foreman-rake-apipie:cache:index]: /usr/sbin/foreman-rake apipie:cache:index returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:45 main]  /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[example.hostname.org]: Failed to call refresh: Proxy example.hostname.org cannot be registered (Could not load data from https://example.hostname.org
[ERROR 2016-02-15 01:30:45 main]  /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[example.hostname.org]: Proxy example.hostname.org cannot be registered (Could not load data from https://example.hostname.org
[ERROR 2016-02-15 01:30:49 main] Repeating errors encountered during run:
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Tftp::Service/Service[tftpd-hpa]: Could not evaluate: undefined method `[]' for nil:NilClass
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Foreman::Database::Postgresql/Postgresql::Server::Db[foreman]/Postgresql::Server::Database[foreman]/Exec[/usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='foreman' --template=template0 --encoding 'utf8' --locale=en_US.utf8  'foreman']: Failed to call refresh: /usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='foreman' --template=template0 --encoding 'utf8' --locale=en_US.utf8  'foreman' returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Foreman::Database::Postgresql/Postgresql::Server::Db[foreman]/Postgresql::Server::Database[foreman]/Exec[/usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='foreman' --template=template0 --encoding 'utf8' --locale=en_US.utf8  'foreman']: /usr/lib/postgresql/9.3/bin/createdb --port='5432' --owner='foreman' --template=template0 --encoding 'utf8' --locale=en_US.utf8  'foreman' returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Foreman::Database::Postgresql/Postgresql::Server::Db[foreman]/Postgresql::Server::Database_grant[GRANT foreman - ALL - foreman]/Postgresql::Server::Grant[database:GRANT foreman - ALL - foreman]/Postgresql_psql[grant:database:GRANT foreman - ALL - foreman]: Could not evaluate: Error evaluating 'unless' clause, returned pid 4080 exit 1: 'ERROR:  database "foreman" does not exist
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]: Failed to call refresh: /usr/sbin/foreman-rake db:migrate returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Foreman::Database/Foreman::Rake[db:migrate]/Exec[foreman-rake-db:migrate]: /usr/sbin/foreman-rake db:migrate returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]: Failed to call refresh: /usr/sbin/foreman-rake db:seed returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]: /usr/sbin/foreman-rake db:seed returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Foreman::Database/Foreman::Rake[apipie:cache:index]/Exec[foreman-rake-apipie:cache:index]: Failed to call refresh: /usr/sbin/foreman-rake apipie:cache:index returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Foreman::Database/Foreman::Rake[apipie:cache:index]/Exec[foreman-rake-apipie:cache:index]: /usr/sbin/foreman-rake apipie:cache:index returned 1 instead of one of [0]
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[example.hostname.org]: Failed to call refresh: Proxy example.hostname.org cannot be registered (Could not load data from https://example.hostname.org
[ERROR 2016-02-15 01:30:49 main]  /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[example.hostname.org]: Proxy example.hostname.org cannot be registered (Could not load data from https://example.hostname.org

```

One line in particular stands out, and points to you being correct about this being a postgres issue:
`
[ERROR 2016-02-15 01:29:19 main]  /Stage[main]/Foreman::Database::Postgresql/Postgresql::Server::Db[foreman]/Postgresql::Server::Database_grant[GRANT foreman - ALL - foreman]/Postgresql::Server::Grant[database:GRANT foreman - ALL - foreman]/Postgresql_psql[grant:database:GRANT foreman - ALL - foreman]: Could not evaluate: Error evaluating 'unless' clause, returned pid 4080 exit 1: 'ERROR:  database "foreman" does not exist`

**Comment by mmoll** [comment] 2016-02-15 21:57
@kierr thanks, please re-run foreman-installer with --debug and post the backtrace.

**Comment by mmoll** [comment] 2016-02-19 22:26
no reaction, closing.

**Closed by mmoll** 2016-02-19 22:26 UTC

**Comment by kierr** [comment] 2016-02-20 00:50
Sorry... I have since moved to manual scripted installation with passenger/nginx with postgresql and puppetmaster and the smart proxy all in separate docker containers, removing the installer from the equation entirely, maybe if the OP returns he can contribute further.

**Comment by mmoll** [comment] 2016-02-20 00:54
@kierr no problem at all :100:

**Comment by kierr** [comment] 2016-05-24 07:37
I'm back, @mmoll. Having forgotten why I went the manual way, I've tried the installer again.

The PostgreSQL locale issue is simply due to missing locale... running `locale-gen --purge en_US.UTF-8` before starting fixes this.

There is a second issue - the nil class error tftpd-hpa one.

I can provide whatever logs/stack traces needed, but `foreman-installer --debug` returns `ERROR: Unrecognised option '--debug'`....

**Comment by mmoll** [comment] 2016-05-24 07:39
maybe just `-d` then? `--help` should work, if `-d` doesn't. There should be more information in the log file then.

**Comment by kierr** [comment] 2016-05-24 07:42
From `--help`:

```
    --log-level LEVEL             Log level for log file output (default: :debug)
```

So it seems we have the debug output by default. I'm using `-v` for verbose output.

**Comment by mmoll** [comment] 2016-05-24 07:45
ok, if there's a backtrace at the console or the log, please paste it, otherwise I'm out of ideas

**Comment by kierr** [comment] 2016-05-24 07:47
Here's the full 3.4k line log: https://gist.github.com/kierr/70fad5a216c32b848798a6d3c0a5d5ae

**Comment by domcleal** [comment] 2016-05-24 07:58
I don't know about the tftp error, but the Foreman one on line 3335 makes it appear that the installer isn't running in a UTF-8 enabled locale. The logs above look like you're not running the installer in an interactive/login session, so perhaps you need to export LANG?

**Comment by mmoll** [comment] 2016-05-24 08:15
per IRC: it's a docker image and that image known to have upstart issues (tftp), I guess that's also the cause of the locale problems...

**Comment by kierr** [comment] 2016-05-24 08:18
Yeah so I was trying this on docker using the official ubuntu image (which has no functioning upstart) and also trying with phusion/baseimage, which has runit as an upstart alternative.

I do already have things semi-functional having installed manually, but trying to dockerize Foreman has proven to be a nightmare! Rather than fight against the tide doing things an unsupported, manual, dev environment way, I will move to KVM or another supported alternative. Case closed! Thanks all!
